name: Python Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout submodule
      uses: actions/checkout@v3
      with:
        repository: EECA-NZ/py-eecadata
        path: py-eecadata
        ssh-key: ${{ secrets.SUBMODULE_DEPLOY_KEY }}
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage
        pip install .
        cd ..
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
  
    - name: Run tests
      run: |
        coverage run -m pytest

    - name: Generate coverage report
      run: coverage report
